name: Docker Build and Push  

on:  
  push:  
    branches:  
      - main  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v3  

      - name: Login to DockerHub  
        uses: docker/login-action@v2  
        with:  
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Build Docker image  
        run: docker build -t mon-utilisateur/my-http-server:latest .  

      - name: Push Docker image  
        run: docker push mon-utilisateur/my-http-server:latest  
